#sudo vim mario.yaml
apiVersion: v1
kind: Pod
metadata:
  name: super-mario
  labels:
   env: dev
spec:
  containers:
  - name: super-mario
    image: abhipraydh96/super-mario
    ports:
    - containerPort: 80
#kubectl apply -f mario.yaml
#kubectl get pods

#sudo vim service.yaml
---
apiVersion: v1
kind: Service
metadata: 
  name: svc-sm
spec:
  selector:
      env: dev
  ports:
   - protocol: "TCP"
     port: 80
     targetPort: 80
  type: NodePort   
#kubectl apply -f service.yaml
#kubectl get svc      